### ISSUE TITLE
Missing git tags

### ISSUE THREAD

**Issue by kloczek** [eukaryote/pytest-tornasync#12]
According to https://pypi.org/project/pytest-tornasync/ latest version is 0.6.0.post2.
However looks like some changes not been commited here (of git repo not pushed) an there is no version git tags.
Is it possible to add missing bots to git repo?

Thx.

**Comment by jnahmias** [comment]
Sames as #9

**Comment by kloczek** [comment]
gentle ping .. 😃

**Comment by frenzymadness** [comment]
one more gentle ping … ;)

**Comment by eukaryote** [comment]
My apologies for the delay. I've added a tag for the current pypi version and will add tags in the future.
