### ISSUE TITLE
Breakage under Tornado 5.0.0

### ISSUE THREAD

**Issue by brettcannon** [eukaryote/pytest-tornasync#2]
Or at least I think so: https://travis-ci.org/brettcannon/gidgethub/builds/349655202?utm_source=github_status&utm_medium=notification

**Comment by eukaryote** [comment]
Thank you for the bug report! My apologies for not seeing and responding to this sooner.

I just released a new version (0.5.0) that works with Tornado 5 (and Pytest >= 3, but Tornado 4 is no longer supported). 

It's on PyPI and also tagged, so downloadable from https://github.com/eukaryote/pytest-tornasync/releases.
