### ISSUE TITLE
Upload sdist to PyPI

### ISSUE THREAD

**Issue by nicoddemus** [eukaryote/pytest-tornasync#5]
Hello,

The last version is available only on [wheels](https://pypi.org/project/pytest-tornasync/#files), would it be possible to upload `sdist` files as well?

Packagers (like conda) need the sdist file to generate their packages.

**Comment by igorcandeia** [comment]
> Hello,
> 
> The last version is available only on [wheels](https://pypi.org/project/pytest-tornasync/#files), would it be possible to upload `sdist` files as well?
> 
> Packagers (like conda) need the sdist file to generate their packages.

@eukaryote you can do this?

**Comment by eukaryote** [comment]
Sorry I didn't see this sooner. I just uploaded an sdist tarball for the last release, and will include both for any future releases.

**Comment by nicoddemus** [comment]
Thanks!
