### ISSUE TITLE
Tags for releases

### ISSUE THREAD

**Issue by toddrme2178** [eukaryote/pytest-tornasync#9]
Currently there are no github tags for releases.  Would it be possible to add them?

Tags have the advantage over sdists that they include all files from the git repo, not just those chosen for the sdist.  In this case, where the test files are not included in sdists (see #8), having the tags makes it feasible for downstream packagers to download a complete version of the sources.

**Comment by jnahmias** [comment]
+1 on this. I'd like to package this for Debian, and having the tags here in github would be very helpful.
--Joe

**Comment by eukaryote** [comment]
My apologies for the delay. I've added a tag for the current pypi version and will add tags in the future.
